from langchain_text_splitters import CharacterTextSplitter

text="""The peacock is one of the most beautiful birds in the world, known for its bright colors and majestic appearance. The male bird is called a peacock, while the female is known as a peahen, and together they are called peafowl. Peacocks are admired for their long, colorful tail feathers, known as a train, which can be more than five feet long. These feathers have eye-shaped designs called ocelli, and when the peacock spreads them like a fan, it creates a stunning display used to attract the peahen. Peacocks are mostly blue and green in color, and their necks shine beautifully in the sunlight. These birds are commonly found in India, Sri Lanka, and Southeast Asia, and the Indian Peacock is the national bird of India. Peacocks live in forests, gardens, and areas close to villages. They eat insects, seeds, fruits, and sometimes small reptiles. A peacock has a loud call that can be heard from far away, and it often sounds like it is saying “Kyaa” or “Mee-ow.” Despite being large birds with long tails, they can fly short distances and usually sleep on tall trees at night to stay safe from predators. The stunning colors of their feathers are not due to pigments but are created by a special reflection of light, a property called structural coloration. Peahens, unlike peacocks, are brown and less colorful, which helps them stay hidden while protecting their eggs. Peafowl are social birds that live in groups and communicate using their feathers and voice. When threatened, they can run fast or fly to safety, and their predators include snakes, wild cats, and foxes. A peacock typically lives for about 15 to 20 years. Every year, it sheds its tail feathers, which grow back again after some months. These feathers are often collected by people for decoration and are used in art, dance costumes, and cultural ceremonies. In Indian culture, the peacock holds great significance and is considered a sacred bird associated with gods, festivals, and royalty. It symbolizes beauty, grace, pride, and immortality. Peacocks have been kept in royal gardens for centuries and continue to attract tourists who enjoy watching them dance, especially in the rain. Their elegance, vibrant colors, and charming behavior make them one of the most admired birds on the planet. Though generally friendly, peacocks may become territorial during the breeding season. They are protected in many regions by wildlife laws, ensuring their survival and continued presence in nature. The peacock remains a timeless symbol of splendor, capturing the imagination of people around the world."""

splitter=CharacterTextSplitter(
    chunk_size=1,
    chunk_overlap=0,
    separator=''
)
result=splitter.split_text(text)
print(result)